services:

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - db

    env_file:
      - .env

  db:
    image: postgres:17

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RANGEROVER
      POSTGRES_DB: ecommerce

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: