services:

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - primary
      - replica

    env_file:
      - .env
    networks:
      - postgres_network

  primary:
    image: postgres:17

    container_name: primary_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RANGEROVER
      POSTGRES_DB: ecommerce

    ports:
      - "5434:5432"

    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf

    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf

    networks:
      - postgres_network

  replica:
    image: postgres:17
    container_name: replica_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RANGEROVER

    ports:
      - "5433:5432"
    
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./replica/setup-replica.sh:/setup-replica.sh

    command: ["/setup-replica.sh"]

    depends_on:
      - primary
    
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    

volumes:
  primary_data:
  replica_data: