

# Local socket connections
local   all             all                                     scram-sha-256

# Localhost
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Allow Docker containers on the bridge network
host    all             all             0.0.0.0/0               scram-sha-256

# Replication
host    replication     replicator      0.0.0.0/0               scram-sha-256